Ajusstar nuevo validador de quality gates

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -48,13 +48,18 @@ steps:
   displayName: 'Sonarqube End'
 
 # Nueva tarea para verificar la calidad de la puerta
-- powershell: |
-    $status = $build.properties['sonarQube.qualityGate.status']
-    if ($status -eq 'FAILED') {
-      Write-Host "SonarQube Quality Gate Failed."
-      exit 1
-    } 
+- task: SonarQubePublish@4
+  inputs:
+    pollingTimeoutSec: '300'
+- script: |
+    if [ "$(Build.Quality)" == "Failed" ]; then
+      echo "SonarQube Quality Gate Failed."
+      exit 1  # Termina el pipeline con un estado de error
+    else
+      echo "SonarQube Quality Gate Passed."
+    fi
   displayName: 'Verificar calidad de la puerta SonarQube'
+
 
 - script: | 
     dotnet test
